### PR TITLE
convert mpi-serial to subtree

### PR DESCRIPTION
**Pull request by rljacob**
Change mpi-serial to be a subtree of the new separate repository for  mpi-serial.
The new mpi-serial repository is https://github.com/MCSclimate/mpi-serial

### CODE REVIEW

**Comment by rljacob** [comment]
I verified --enable-mpiserial still works in the MCT configure on blues.

**Comment by jayeshkrishna** [comment]
@rljacob : Is "make install" supposed to work with MCT (make completes successfully)?

**Comment by jayeshkrishna** [comment]
configure with "--enable-mpiserial" and make completed successfully on blues+gnu

**Comment by rljacob** [comment]
Yes make install should work as long as you have write permission to the target dir.

**Comment by jayeshkrishna** [comment]
I did my configure on blues with "--prefix" to point to local install dir but "make install" failed with the following error message,
```
make[1]: Entering directory `/blues/gpfs/home/jayesh/acme/MCT/mpi-serial'
make[1]: Nothing to be done for `default'.
make[1]: Leaving directory `/blues/gpfs/home/jayesh/acme/MCT/mpi-serial'
make[1]: Entering directory `/blues/gpfs/home/jayesh/acme/MCT/mpeu'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/blues/gpfs/home/jayesh/acme/MCT/mpeu'
make[1]: Entering directory `/blues/gpfs/home/jayesh/acme/MCT/mct'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/blues/gpfs/home/jayesh/acme/MCT/mct'
make[1]: Entering directory `/blues/gpfs/home/jayesh/acme/MCT/mpi-serial'
make[1]: *** No rule to make target `lib', needed by `install'.  Stop.
make[1]: Leaving directory `/blues/gpfs/home/jayesh/acme/MCT/mpi-serial'
make: *** [install] Error 2

```

**Comment by rljacob** [comment]
Ok.  Please make a new issue about "make install" not working.

**Pull request merged**
