### PR TITLE
Fix for building m_AttrVect.F90 using Cray compilers

### LINKED ISSUE #68: Cray compilers don't like old directives
Reported by Sarat Sreepathi

Trying to build E3SM on a Cray testbed, I ran into the following issue with a workaround. 

Issue:
```
ftn-855 crayftn: ERROR M_ATTRVECT, File = ../../../home/users/coe0149/repos/E3SM/cime/src/externals/mct/mct/m_AttrVect.F90, Line = 67, Column = 9 
  The compiler has detected errors in module "M_ATTRVECT".  No module information file will be created for this module.

ftn-1381 crayftn: ERROR EXPORTIATTR_, File = ../../../home/users/coe0149/repos/E3SM/cime/src/externals/mct/mct/m_AttrVect.F90, Line = 1952 
  A statement must not appear between the COLLAPSE directive and the DO loop that follows it. 

Cray Fortran : Version 9.1.3 (20200225214845_454c23bd9080e42515651f42b36ba77db1022811)
Cray Fortran : Compile time:  0.1501 seconds
Cray Fortran : 4138 source lines
Cray Fortran : 2 errors, 0 warnings, 0 other messages, 0 ansi
Cray Fortran : "explain ftn-message number" gives more information about each message.
gmake[1]: *** [m_AttrVect.o] Error 1
```

Workaround: Removing two lines with  **!DIR$ COLLAPSE**
I presume they are expected to be commented out but they trigger the Cray compiler.
```
diff --git a/cime/src/externals/mct/mct/m_AttrVect.F90 b/cime/src/externals/mct/mct/m_AttrVect.F90
index d186fb8..82931d1 100644
--- a/cime/src/externals/mct/mct/m_AttrVect.F90
+++ b/cime/src/externals/mct/mct/m_AttrVect.F90
@@ -845,7 +845,6 @@
   if(myZeroInts) then ! zero out INTEGER attributes
      if(List_allocated(aV%iList)) then
         if(associated(aV%iAttr) .and. (nIAttr_(aV)>0)) then
-!DIR$ COLLAPSE
            aV%iAttr=0
         endif
      endif
@@ -854,7 +853,6 @@
   if(myZeroReals) then ! zero out REAL attributes
      if(List_allocated(aV%rList)) then
         if(associated(aV%rAttr) .and. (nRAttr_(aV)>0)) then
-!DIR$ COLLAPSE
            aV%rAttr=0._FP
         endif
```

Related issue: https://github.com/E3SM-Project/E3SM/issues/3509
Please let me know if this issue needs to be replicated in this repo.

There was a similar line (albeit lowercase) in m_MatAttrVectMul.F90 that did not trigger the above problem.

### PR DESCRIPTION
**Pull request by sarats**
Remove 2 compiler directives that Cray compiler didn't like.

Fixes #68

### CODE REVIEW

**Comment by sarats** [comment]
Looking at the history for this file (https://github.com/MCSclimate/MCT/blame/master/mct/m_AttrVect.F90), I noticed @amametjanov replaced the earlier directives with these.

Update !CDIR COLLAPSE with !DIR$ COLLAPSE from 
https://github.com/MCSclimate/MCT/commit/9430d8271c000a8ae8df6751ab4188616bf62c99

I typically expect collapse directives before loops. Anyway, I hope these can be removed if they are no longer used/useful.

**Comment by sarats** [comment]
Digging a bit more, I found that these directives were initially added by @rljacob for vectorization using Fujitsu compilers 17 years ago! 
https://github.com/MCSclimate/MCT/commit/97f3ab00ca918f2d30c85edd7195e8391d3a32fb

**Comment by rljacob** [comment]
Ha!  Those mods were given to me by someone at Fujitsu.

**Comment by sarats** [comment]
Please let me know if anything else is needed to merge this upstream.

**Comment by rljacob** [comment]
My MCT standalone testing is currently suffering because of some old MPI-1 features in the system test.  If you need this quickly, make the same PR to CIME.

**Comment by sarats** [comment]
No rush, can wait till MCT testing is done.

**Comment by naromero77** [comment]
@sarats Did you report this bug to Trey White from Cray?

Just coincidentally -- this is similar to a bug I see with the f18 compiler when compiling the PICSAR code. Some really old Intel-specific directives that should be completely ignored by f18 cause a compile-time failure. Here is an example of what I am talking about:

https://github.com/flang-compiler/f18/issues/948

**Comment by sarats** [comment]
Just a friendly reminder, still no rush.

**Comment by naromero77** [comment]
Rob suggested that if you need this quickly, to make the PR into E3SM/CIME. But isn't this a bug in the Cray compiler -- it should just ignore directives that are specific to other vendors.

**Comment by sarats** [comment]
In this case, I'm not quite sure what the collapse directive is aiming to do in the absence of a loop. 

If MCT testing is still an issue, I guess I can make a PR to CIME.

**Comment by rljacob** [comment]
Passed system test.

**Pull request merged**
